
import java.awt.Color;
import java.time.Clock;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dawoud
 */
public class AddFullEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddFullEmployee
     */
    // ATTRIBUTES
    
    public ArrayList<EmployeeInfo>[] buckets;
    private MyHashTable mainHT;

    String firstName = "-1";
    String lastName = "-1";

    int employeeNum = -1;
    int g = -1;
    int wLNum = -1;

    double deductRate = -1.0;
    //public double weeklySalary = -1.0;
    double yearlySalary = -1.0;

    public AddFullEmployee() {
        initComponents();
        //setExtendedState(getExtendedState() | JFrame.MAXIMIZED_VERT);
    }
    
    // Meathod Overload
    public AddFullEmployee(int eNum, String fName, String lName, int g, int wLoc, double dRate, double ySalary) {
        initComponents();
            eN.setText(String.valueOf(eNum));
            fN.setText(fName);
            lN.setText((lName));
            wL.setSelectedIndex(wLoc);
            dR.setText(String.valueOf(dRate));
            yS.setText(String.valueOf(ySalary));
            
            if (g == 0) {
                m.setSelected(true);
            } else if (g == 1) {
                f.setSelected(true);
            }
                        
        //setExtendedState(getExtendedState() | JFrame.MAXIMIZED_VERT);
    }

    // METHODS   

    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        lN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dR = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        yS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eN = new javax.swing.JTextField();
        wL = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Full Time Empoyee Fourm");

        jLabel15.setText("Last Name");

        fN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNActionPerformed(evt);
            }
        });

        jLabel13.setText("Gender");

        buttonGroup1.add(m);
        m.setText("Male");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        buttonGroup1.add(f);
        f.setText("Female");

        jLabel14.setText("First Name");

        jLabel16.setText("Work Location");

        jLabel17.setText("Deduct Rate");

        dR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRActionPerformed(evt);
            }
        });

        jLabel19.setText("Yearly Salary");

        jButton1.setText("ADD EMPLOYEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee Number");

        wL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Mississauga", "Bramton", "Toronto", "Markham" }));
        wL.setToolTipText("");
        wL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m)
                                    .addComponent(f))
                                .addGap(121, 121, 121)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(wL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fN)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(lN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(dR, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yS, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(eN)
                            .addGap(196, 196, 196))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(fN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(6, 6, 6)
                        .addComponent(dR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(eN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNActionPerformed

    private void dRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // First Name
        
        if (fN.getText() != null) {
            firstName = fN.getText();

        } else {
            JOptionPane.showMessageDialog(this, "Please Enter A First Name");
        }

        // Last Name
        
        if (lN.getText()!= null) {
            lastName = lN.getText();

        } else {
            JOptionPane.showMessageDialog(this, "Please Enter A Last Name");
        }

        //Employee Number
        if (eN.getText() != null) {
            String eNum = eN.getText();
            employeeNum = Integer.parseInt(eNum);
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter A Employee Number");
        }
        // Deduct Rate

        if (dR.getText() != null) {
            String DNum = dR.getText();
            deductRate = Double.parseDouble(DNum);
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter A Deduct Rate");
        }

//        // Weekly Salary
//        if (wS.getText() != null) {
//            String wNum = wS.getText();
//            yearlySalary = Double.parseDouble(wNum);
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Please Enter A Weekly Salary");
//        }

        // Yearly Salary
        
        if (yS.getText() != null) {
            String YNum = yS.getText();
            yearlySalary = Double.parseDouble(YNum);
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter A Yearly Salary");
        }

        // Gender
        if (m.isSelected()) {
            g = 0;
        }
        else if (f.isSelected()) {
            g = 1;
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter A Gender");
        }

        // Work Location 
        String wLSelected = wL.getSelectedItem() + "";

        if (wLSelected.equals("Please Select")) {
            JOptionPane.showMessageDialog(this, "Please Enter A Work Location");
        }
        if (wLSelected.equals("Mississauga")) {
            wLNum = 1;
        }
        if (wLSelected.equals("Bramton")) { 
            wLNum = 2;
        }
        if (wLSelected.equals("Toronto")) {
            wLNum = 3;
        }
        if (wLSelected.equals("Markham")) {
            wLNum = 4;
        }

        if (firstName.equals("-1") == false && lastName.equals("-1") == false
                && employeeNum != -1 && g != -1 && wLNum != -1 && deductRate != -1.0 && yearlySalary != -1.0) {
            FTE theFTE;
            theFTE = new FTE(employeeNum, firstName, lastName, g, wLNum, deductRate, yearlySalary);
            mainHT.addEmployee(theFTE);
            JOptionPane.showMessageDialog(this, "Added The Full Time Employee To The Data Base");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void wLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFullEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFullEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFullEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFullEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFullEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dR;
    private javax.swing.JTextField eN;
    private javax.swing.JRadioButton f;
    private javax.swing.JTextField fN;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField lN;
    private javax.swing.JRadioButton m;
    private javax.swing.JComboBox<String> wL;
    private javax.swing.JTextField yS;
    // End of variables declaration//GEN-END:variables
}
